name: video_viewer
description: Multiplatform minimalist video viewer with spectacular user experience.
homepage: https://github.com/seel-channel/video_viewer
version: 1.2.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^1.0.0
  helpers: ^1.1.4
  http: ^0.13.4
  path_provider: ^2.0.6
  provider: ^6.0.5
  video_player: ^2.7.0
  volume_watcher: ^2.0.1
  wakelock: ^0.6.2
  video_player_web_hls: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
